name: sqd-nitrogen
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2.0
  - scipy
  - matplotlib
  - pyscf
  - qiskit
  - qiskit-ibm-runtime
  - qiskit-addon-sqd
  - rustworkx
  - ffsim
  - jupyterlab
