name: sqd-nitrogen
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.*
  - scipy
  - matplotlib
  - pyscf
  - qiskit
  - qiskit-ibm-runtime
  - rustworkx
  - ffsim
  - pip
  - pip:
      - qiskit-addon-sqd
  - jupyterlab
